Update source.csv
iP1SMS/disposable-phone-numbers pull request #20
Opened 2023-05-25 14:25 UTC by patbro01

Added newly discovered pages

2023-05-25 14:28 UTC, Wikxen requested changes

2023-05-25 14:28 UTC, Wikxen commented on source.csv
> +https://mytempsms.com/
```suggestion
https://mytempsms.com/
https://mytempsms.com/receive-sms-online/phone-number/page/2.html
https://mytempsms.com/receive-sms-online/phone-number/page/3.html
https://mytempsms.com/receive-sms-online/phone-number/page/4.html
https://mytempsms.com/receive-sms-online/phone-number/page/5.html
https://mytempsms.com/receive-sms-online/phone-number/page/6.html
```

2023-05-25 14:33 UTC, Wikxen approved these changes

2023-05-29 08:27 UTC, merged

2024-07-30 12:44 UTC, mrT23 commented
## PR Code Suggestions ✨

No code suggestions found for the PR.

2024-07-30 13:50 UTC, mrT23 commented
## PR Code Suggestions ✨

No code suggestions found for the PR.